### ISSUE TITLE
Return `Result`s instead of panicking

### ISSUE THREAD

**Issue by devtomio** [JoshKarpel/fungoid#18]
This allows users to handle their own errors.

**Comment by JoshKarpel** [comment]
Agreed; this has been on my to-do list for a while.

**Comment by devtomio** [comment]
If you want to I can work on this.

**Comment by JoshKarpel** [comment]
Sure! That would help with #14.

I'm not sure exactly which places you're referring to, but the vague idea I've had in my head is that the core change is for https://github.com/JoshKarpel/fungoid/blob/main/src/execution.rs#L137 to return a `Result`, and all the operations inside it that currently `.expect()` or `panic!` should return errors instead. I imagine that change will need to be propagated to a variety of places.

Note: I seem to have messed up the implementation for `&` and `~` (get input from stdin) and they don't seem to work when actually running from a terminal, but they should work in tests, e.g. the one I'm adding in #14 as part of some general housekeeping https://github.com/JoshKarpel/fungoid/pull/14/files#diff-89d6c639b6a289bfcef8c9380528aa0f8118eeb19a65500845ed92b9ef4b0472R359
